# Generated by Django 3.2.7 on 2021-11-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20211111_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_photo',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
