# Generated by Django 2.2.12 on 2022-04-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_auto_20220404_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=50)),
                ('stud_email', models.EmailField(max_length=254)),
                ('stud_password', models.CharField(max_length=20)),
                ('stud_mobile', models.BigIntegerField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
